### ISSUE TITLE
light bug

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#436] opened 2021-08-30 16:39 UTC
https://youtu.be/BfkVDg5vuwU

**Comment by draconisPW** [comment] 2021-08-30 16:42
Surely due to latest lighting changes ported from V, I'll take a look at this while checking recent changes to V code to see if there's a fix.

**Comment by igroglaz** [comment] 2021-08-30 16:44
Another demo by admin char: https://www.youtube.com/watch?v=gOK7fXpuHd4

**Comment by draconisPW** [comment] 2021-08-31 12:48
Yeah I can reproduce this easily with any char and simply running around in the dungeon (torchlight squares while running, then lit squares when stopping).

**Comment by draconisPW** [comment] 2021-09-02 09:14
Unfortunately nothing on the V side. Will have to find and fix this myself :(

**Comment by draconisPW** [comment] 2021-09-02 09:16
Looking at the first video (and my personal experience), it seems this happens when switching panels. I'll investigate that.

**Comment by draconisPW** [comment] 2021-09-02 09:42
Also happens when canceling running (calling disturb) or pressing R to redraw the screen. This clearly means there is a "refresh lighting" missing when walking. Checking this now.

**Comment by draconisPW** [comment] 2021-09-02 10:15
Only SQUARE_SEEN squares that are not SQUARE_WASSEEN are updated when walking (any disturbance will set PR_MAP to redraw the whole screen so this is fine). The bug occurs because some features are still SQUARE_WASSEEN and therefore don't trigger the update.

**Comment by draconisPW** [comment] 2021-09-02 12:12
First problem fixed: SQUARE_WASSEEN was set globally (cave) when it should have been set per player. This is fixed, but doesn't fix the issue, since the SQUARE_SEEN is still set on some feature, so an update is still required (case 1: seen -> unseen or unseen -> seen is managed, case 2: lit -> unlit or unlit -> lit is not managed).

**Comment by draconisPW** [comment] 2021-09-02 12:52
Strangely this doesn't happen in V, also it's the same code.

**Comment by igroglaz** [comment] 2021-09-02 13:23
Maybe it's cause we changed yellow light thingy in the past https://github.com/draconisPW/PWMAngband/issues/113

**Comment by draconisPW** [comment] 2021-09-02 13:28
Fixed the part where lit -> unlit or unlit -> lit was not updated by introducing a new SQUARE_WASCLOSE flag similar to the SQUARE_WASSEEN flag used for seen -> unseen or unseen -> seen. This fixes the problem nicely, except when walking adjacent to a wall for some reason :(

**Comment by draconisPW** [comment] 2021-09-03 09:08
Ok the wall tile that is a knight's move away from the player isn't updated (lit -> torchlit) when moving. This should be pretty easy to spot in the code.

**Comment by draconisPW** [comment] 2021-09-03 09:14
Plus this only happens when using a lamp or an artifact light source. Torches and lanterns work fine.

**Comment by draconisPW** [comment] 2021-09-03 13:38
This *should* be fixed now...

**Closed by draconisPW** 2021-09-03 13:38 UTC
Labels: bug
