### ISSUE TITLE
server crush upon room creation

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#383] opened 2021-06-21 13:44 UTC
[01:16] Dawndeath: probably a mimic
[01:16] Dawndeath: cos line above sets floor
[01:17] Dawndeath: square_is_empty = floor with no trap, no object and no monster
[01:26] Dawndeath: i'll make tests tomorrow with forcing that room and see if it's a mimic

**Comment by draconisPW** [comment] 2021-06-21 15:45
Ah yeah need to remember this...

**Comment by draconisPW** [comment] 2021-06-21 16:29
Unfortunately I didn't manage to reproduce the problem :(

**Comment by igroglaz** [comment] 2021-06-21 18:25
Should we include certain debug code to catch it?

**Comment by draconisPW** [comment] 2021-06-22 06:55
Replace
my_assert(square_isempty(c, &grid));
with
if (!square_isempty(c, &grid))
{
int crush = 0;
}"
and put a breakpoint on the "crush" line
If I have time I'll try the same, but it'll be easier to debug on the server since we didn't check which dungeon it occured and it could happen only one out of a billion generated levels.

**Comment by draconisPW** [comment] 2021-06-22 08:47
Tried with Tangaria setup inside usual dungeons... still couldn't reproduce. I cannot see how the squares inside room template can be non-floor since the code sets floor just before. Need to try the above debug code and put breakpoint to reproduce directly on the server and we'll check when the server stops responding, meaning the breakpoint has been reached. This is vital to get info about grid, feature on grid, monster on grid, and so on...

**Comment by igroglaz** [comment] 2021-06-22 12:10
Cool idea with int crush! Did it :) Lets fish!

**Comment by draconisPW** [comment] 2021-07-22 07:41
Punting to next release as I can't reproduce this.

**Comment by draconisPW** [comment] 2022-01-20 07:51
Cloud room template was incorrectly designed with a space tile instead of a floor tile, this is now fixed.

**Closed by draconisPW** 2022-01-20 07:51 UTC
Labels: bug
