### ISSUE TITLE
Linux server doesn't save server, player state

### ISSUE THREAD

**Issue by s88100** [draconisPW/PWMAngband#318] opened 2021-03-14 08:13 UTC
src/server/savefile.c  save_player(), save_dungeon_special(), save_server_info(), save_account_info()
doesn't save files
~/.pwmangband/PWMAngband/save/Player(username)
~/.pwmangband/PWMAngband/save/players
~/.pwmangband/PWMAngband/save/server
I uploaded files(/lib/user/save/) from windows server to linux, player account are loaded but not saved.

`#ifdef SETGID`
_if we are running as a central install on a multiuser system that has setgid support._ https://en.wikipedia.org/wiki/Setuid

https://github.com/draconisPW/PWMAngband/blob/master/src/server/savefile.c#L520
```
bool save_player(struct player *p)
{
..........
    /* Open the savefile */
    strnfmt(new_savefile, sizeof(new_savefile), "%s%u.new", p->savefile, Rand_simple(1000000));
plog("Test-1");
    while (file_exists(new_savefile) && (count++ < 100))
    {
plog("Test-2");
        strnfmt(new_savefile, sizeof(new_savefile), "%s%u%u.new", p->savefile,
            Rand_simple(1000000), count);
plog("Test-3");
    }
    file = file_open(new_savefile, MODE_WRITE, FTYPE_SAVE);
plog("Test-4");
    if (file)
    {
plog("Test-5");
        file_write(file, (char *)&savefile_magic, 4);
        file_write(file, (char *)&savefile_name, 4);

        character_saved = try_save((void *)p, file, (savefile_saver *)player_savers,
            N_ELEMENTS(player_savers));
        file_close(file);
plog("Test-6");
    }
```

in terminal prints only
140321 140934 Test-1
140321 140934 Test-4

function strnfmt() uses vstrnfmt()
/src/common/z-form.c  added `plog("Test");` to all functions
in vstrnfmt()  strnfcat() server hangs 'segmentation fault'

140321 164932 vstrnfmt_Test
segmentation fault

140321 165112 strnfcat_Test
segmentation fault

if in vstrnfmt() remove `return (n);`
in terminal shows
140321 185731 Game Restarted
Unable to open /home/user/ for writing!
segmentation fault

**Comment by draconisPW** [comment] 2021-03-16 15:16
Adding SETGID support, let's see if it changes anything...

**Comment by draconisPW** [comment] 2021-03-16 15:51
I've modified save_player() so it matches V code. It will need testing to see if it changes anything. If it works, I'll update the other saving functions.

**Comment by s88100** [comment] 2021-03-16 18:08
the bug remained

removed the code from angband
`safe_setuid_grab(); , safe_setuid_drop(); , #ifdef SETGID`
in main.c, savefile.c, z-file.c
angband saves player state

**Comment by draconisPW** [comment] 2021-03-17 08:00
Yeah was obvious it was not the problem, since SETGID is commented out in V. I'll revert the change and look why file_exists() doesn't work.

**Comment by draconisPW** [comment] 2021-03-17 11:04
Unfortunately I can't do much since I don't have any way to test anything...

file_exists() is using exactly the same code as V. I don't even know which part is called -- HAVE_STAT or not.

**Comment by draconisPW** [comment] 2021-03-17 13:51
vstrnfmt() is also totally identical to V

**Comment by igroglaz** [comment] 2021-03-17 14:46
@flambard-took , @CBlueGH , @mhirki - guys, maybe you know what could be the problem? Help us please :)

**Comment by backwardsEric** [comment] 2021-03-17 17:25
Since the file hierarchy for where the saves are stored was transferred from Windows, I would suspect that the directory permissions are not set appropriately, and whatever account the server is running as (or whatever identity it drops down to with safe_setuid_grab()) does not have permission to write or create a file in those directories.  Adding an else clause to the "if (file) {" part like this:

`if (file) {
...
} else {
    plog_fmt("Opening %s failed: %s", new_savefile, strerror(errno));
}`

could help verify that the problem is indeed one with permissions on the directories (the declaration for strerror() is in <string.h> and the declaration for errno is in <errno.h> if those haven't already been pulled in).

**Comment by draconisPW** [comment] 2021-03-17 21:42
download VirtualBox Image https://www.linuxvmimages.com/images/xubuntu-2004/

unzip Xubuntu_20.04.1_VB.zip
open Xubuntu_20.04.1_VB_LinuxVMImages.COM.ova in window press import
press 'Start'
edit Network press ok

LOGIN DETAILS
Username: xubuntu
Password : xubuntu
(to become root, use sudo su -)

virtualbox to share clipboard: Devices>Shared Clipboard>Bidirectional (reboot virtualbox)

open Terminal

sudo apt-get update
sudo apt-get install build-essential autoconf libsdl1.2debian libsdl-ttf2.0-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libncurses5-dev
wget https://raw.githubusercontent.com/igroglaz/Tangaria/master/tangaria-setup.sh
chmod +x ./tangaria-setup.sh
./tangaria-setup.sh
Install >>>------>

after reboot Xubuntu, game-launcher will appear in the 'Games' menu
or run in game folder pwmangband-launcher.sh, pwmangclient-launcher.sh

you can edit the script CHECKLIST_UPDATE _... = OFF so as not to download again and unpack with replacement.
in File Manager press Ctrl+h to show all hidden files

number of CPU's in the Virtual Machine https://youtu.be/sB_5fqiysi4?t=411
install VirtualBox Guest Additions in Linux
in the VirtualBox window menu bar, select Devices > Insert Guest Additions CD image.
in terminal drag-n-drop (from cd) autorun.sh
sudo reboot
(VirtualBox) Devices > Drag and Drop > Bidirectional

you can use package manager
sudo apt-get install synaptic
System>Synaptic Package Manager
GNU Debugger — gdb https://cs.baylor.edu/~donahoo/tools/gdb/tutorial.html

**Comment by s88100** [comment] 2021-03-18 08:04
GDB Documentation https://www.gnu.org/software/gdb/documentation/
Remote Debugging using gdbserver https://gcc.gnu.org/onlinedocs/gcc-4.6.4/gnat_ugn_unw/Remote-Debugging-using-gdbserver.html

user preferences are stored in /home/xubuntu/.pwmangband/PWMAngband/ , or link /home/xubuntu/Tangaria/user
in File Manager press Ctrl+h and edit file /home/xubuntu/.pwmangrc > host=localhost
in Terminal
cd '/home/xubuntu/Tangaria/games'
gdb pwmangband
(gdb) run

open client for test
in Terminal Ctrl+c for end process

Program received signal SIGINT, Interrupt.
0x00007ffff7d8c0da in __GI___select (nfds=5, readfds=0x7fffffffde50, 
    writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:41
41	../sysdeps/unix/sysv/linux/select.c: No such file or directory.

(gdb) quit

**Comment by draconisPW** [comment] 2021-03-18 08:39
Can't do anything, the VM doesn't have root password :(

**Comment by draconisPW** [comment] 2021-03-18 09:08
The VM now works.

180321 050016 Opening /home/xubuntu//.pwmangband/PWMAngband/save/PowerWyrm887374.new failed: No such file or directory

**Comment by draconisPW** [comment] 2021-03-18 10:10
Important note: the "account" file is properly created in the same directory, so it's probably not a problem of permissions. I need to look if there is a difference between the code that saves the account file and the savefile routines.

**Comment by draconisPW** [comment] 2021-03-18 10:58
For the account file:
fh = file_open(filename, MODE_APPEND, FTYPE_TEXT);

For the savefile routines:
file = file_open(new_savefile, MODE_WRITE, FTYPE_SAVE);

If I change FTYPE_SAVE to FTYPE_RAW, the file is properly saved.

**Comment by draconisPW** [comment] 2021-03-18 11:29
fd = open(buf, O_CREAT | O_EXCL | O_WRONLY | O_BINARY, S_IRUSR | S_IWUSR);

180321 072248 open /home/xubuntu/.pwmangband/PWMAngband/save/PowerWyrm918526.new failed: No such file or directory

**Comment by draconisPW** [comment] 2021-03-18 13:11
From open() man:

ENOENT O_CREAT is not set and the named file does not exist.
ENOENT A directory component in pathname does not exist or is a
              dangling symbolic link.

I don't think the pathname is a symbolic link, so it must be a problem with O_CREAT.

**Comment by draconisPW** [comment] 2021-03-18 13:14
180321 091222 O_CREAT 0 O_EXCL 0 O_WRONLY 1 O_BINARY 0

Those flags are not set... that's why we get an error.

#define	O_CREAT		0x0200		/* create if nonexistant */
#define	O_EXCL		0x0800		/* error if already exists */
(O_BINARY is unknown and probably not used)

**Comment by draconisPW** [comment] 2021-03-18 13:43
Still doesn't work. If I create the file using FTYPE_RAW then save using FTYPE_SAVE, open() returns a valid descriptor, which means that O_CREAT is still not set.

**Comment by draconisPW** [comment] 2021-03-18 13:55
180321 095213 O_CREAT 64 O_EXCL 128 O_WRONLY 1 O_BINARY 0
180321 095213 open /home/xubuntu/.pwmangband/PWMAngband/save/PowerWyrm950948.new failed: 17 File exists

Values were not the ones used. Because they were defined BEFORE the inclusion of <fcntl.h>

**Comment by draconisPW** [comment] 2021-03-18 14:20
Player savefiles are now saved. Waiting to see if server savefiles are also saved.

**Comment by draconisPW** [comment] 2021-03-18 14:38
Server savefiles are also saved. This is now fixed.

**Closed by draconisPW** 2021-03-18 14:38 UTC
Labels: bug
