### ISSUE TITLE
corrupted savefile

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#221] opened 2020-07-02 07:10 UTC
I've changed this three tiny things:
https://github.com/igroglaz/Tangaria/commit/b1ed2b32ee707698e3e060c728c4f2311270c5d5
https://github.com/igroglaz/Tangaria/commit/ca7087f9872d03574d1df2e03e2d4eb9959c9158
https://github.com/igroglaz/Tangaria/commit/27e82c36a89c22f217d9ee5f4d6c38020c3aad3c

and now server crushes with:

```
020720 100232 Initializing constants...
020720 100232 Initializing projections...
020720 100232 Initializing timed effects...
020720 100232 Initializing player properties...
020720 100232 Initializing features...
020720 100233 Initializing wilderness feats...
020720 100233 Initializing wilderness info...
020720 100233 Initializing town feats...
020720 100233 Initializing towns...
020720 100233 Initializing dungeons...
020720 100233 Initializing object bases...
020720 100233 Initializing slays...
020720 100233 Initializing brands...
020720 100233 Initializing monster pain messages...
020720 100233 Initializing monster bases...
020720 100233 Initializing summons...
020720 100233 Initializing curses...
020720 100233 Initializing activations...
020720 100233 Initializing objects...
020720 100233 Initializing ego-items...
020720 100233 Initializing history charts...
020720 100233 Initializing bodies...
020720 100233 Initializing player races...
020720 100233 Initializing dragon breeds...
020720 100233 Initializing magic realms...
020720 100233 Initializing player classes...
020720 100233 Initializing DM starting items...
020720 100233 Initializing artifacts...
020720 100233 Initializing object properties...
020720 100233 Initializing object power calculations...
020720 100233 Initializing blow methods...
020720 100233 Initializing blow effects...
020720 100233 Initializing monster spells...
020720 100233 Initializing monsters...
020720 100233 Initializing monster pits...
020720 100233 Initializing traps...
020720 100233 Initializing chest_traps...
020720 100233 Initializing quests...
020720 100233 Initializing flavours...
020720 100233 Initializing socials...
020720 100233 Initializing hints...
020720 100233 Initializing random names...
020720 100233 Initializing dungeon profiles...
020720 100233 Initializing room templates...
020720 100233 Initializing vaults...
020720 100233 Initializing player presets...
020720 100233 Initializing other stuff...
020720 100233 Initializing randarts...
020720 100233 Initializing RNG...
020720 100233 Initialization complete
020720 100233 Please wait...
020720 100233 Cannot place object at row 7, column 49!
020720 100233 Savefile is corrupted or too old -- couldn't load block objects
020720 100233 Broken server savefile
020720 100316 Game Restarted
020720 100316 Initialised exit save handler.
```

if I delete server file (\lib\user\save\server) - everything works alright.

Is it possible to fix this? Either way all houses will have to be deleted :(

**Comment by igroglaz** [comment] 2020-07-02 07:12
link to server file https://cdn.discordapp.com/attachments/662334347163992104/728145833060728922/server

**Comment by draconisPW** [comment] 2020-07-02 07:41
The problem is that if for any reason an object cannot be placed the server refuses to run instead of simply discarding the faulty object. I'll try to see why this object cannot be placed (it's probably because the floor has no OBJECT flag now).

**Comment by draconisPW** [comment] 2020-07-02 08:12
Faulty object is some pebbles located at position (49,7) in Ettenmoors at depth 1500ft. Square at (49,7) is "tree h larch small", which cannot have object.

**Comment by draconisPW** [comment] 2020-07-02 08:50
Looking at your stream I didn't see any pebbles at that position when you looked around with the admin, which makes me think the changes you made shifted the saved object list. The pebbles were also marked as "ORIGIN_SPECIAL" (found in a special room) while there were no special rooms around.

**Comment by igroglaz** [comment] 2020-07-02 08:54
Good find! I've fixed this terrain (and some others): https://github.com/igroglaz/Tangaria/commit/74e66526f1ba957fbb6d282bb4be9e32ec52d32f

...but server still doesn't start:

020720 115257 Initializing randarts...
020720 115257 Initializing RNG...
020720 115257 Initialization complete
020720 115257 Please wait...
020720 115257 Cannot place object at row 51, column 155!
020720 115257 Savefile is corrupted or too old -- couldn't load block objects
020720 115257 Broken server savefile

**Comment by draconisPW** [comment] 2020-07-02 09:16
It is not a terrain problem, it's a problem in the object list. The server cannot start because of 3 objects: (49,7) + (66,51) + (155,51). For now, you can just edit load.c and remove "return -1;" at line 1348, so the server will just discard the object without stopping.

**Comment by igroglaz** [comment] 2020-07-02 09:25
Removed return -1 and it works, thanks. So it's a new bug we found?

**Comment by draconisPW** [comment] 2020-07-02 10:16
No idea. I've had this issue before, but couldn't really track the problem.

**Comment by draconisPW** [comment] 2020-07-02 10:22
Workaround for now: don't close VERSION_BETA servers if an object cannot be placed, but just discard the object.

**Closed by draconisPW** 2020-07-02 10:22 UTC
