### ISSUE TITLE
superfast shooting into sleeping monsters

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#2] opened 2019-10-22 21:33 UTC
superfast shooting into sleeping monsters:
https://youtu.be/k2D81LW3GwI?t=1823

**Comment by draconisPW** [comment] 2019-10-23 07:35
Sounds like an overflow in the fractional shot code. I'll look at it.

**Comment by draconisPW** [comment] 2019-10-24 13:05
Probably fixed in 9984212.

**Comment by igroglaz** [comment] 2019-10-26 18:44
It seems it's still there. On my russian sream today: https://www.youtube.com/watch?v=PVADDU1IY58
I've noticed that sometimes when I shot into sleeping monsters my attack speed was bigger then should be

**Comment by draconisPW** [comment] 2019-10-28 16:50
Bug is hard to track (happening 1-2 times per hour). Going to simplify fire-till-kill and see if it changes anything.

**Comment by draconisPW** [comment] 2019-10-29 12:31
Ok I checked the shooting code and this has nothing to do with it. Just seems that sometimes time passes very quickly while using fire-till-kill.

**Comment by igroglaz** [comment] 2019-10-29 13:36
Archer won't complain :bow_and_arrow: I've sent you my config in discord PM

**Comment by draconisPW** [comment] 2019-10-29 14:42
Ok I think I got it... monster moving or appearing should trigger "disturb" if disturb_near is set. This option is almost always set, since removing it would make mobs act in a "Benny Hill" fashion (running at the same pace as the player when the player runs). The only time I remove it is when using the admin char running around in the wilderness since I don't want to stop for every mob.
But in the case of fire_till_kill, I removed the "disturb" call because "disturb" would cancel fire_till_kill. The only problem... not calling "disturb" doesn't cancel running. I should have watched the video more carefully, because clearly you've pressed "running" before "shooting". In that case, since the running is not canceled, everything happens 5x as fast as usual until the char is disturbed again.

**Comment by draconisPW** [comment] 2019-10-29 15:00
Finally was able to reproduce the problem. This happens only when the following conditions are met:
- character is running
- character encounters a monster in the dungeon
- player has macroed the "h" command (this doesn't happen when using "h" directly because running prevents using the command) nd is using the macro while running

**Comment by draconisPW** [comment] 2019-10-29 15:26
Should be finally fixed in 4e463ca.

**Closed by draconisPW** 2019-10-29 15:26 UTC
Labels: bug
