### ISSUE TITLE
Death screen without death

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#561] opened 2022-07-02 09:56 UTC
[17:00] Azken Zutik: Rip that wasn't a rip. Though I almost died from starvation before I realized my character was still alive and could cast remove hunger.  Had just activated a light source ability that requires hunger, and was in the middle of switching it out for my other light source.

![Capture](https://user-images.githubusercontent.com/39904162/176995624-361d85e0-7dda-4a9e-9d98-fd1cde62bb71.png)

Explanation:
[01:15] Azken Zutik: Was on low hunger, so about 15% or less, had just entered a new floor in the Maze, killed a handful of monsters and then activated this:

![1](https://user-images.githubusercontent.com/39904162/176995641-fac51086-d33f-4d2d-ad4f-4ac291a2d872.png)

[01:16] Azken Zutik: Then, I immediately tried to switch to this while still under effects of previous light:

![2](https://user-images.githubusercontent.com/39904162/176995661-7063e614-a4bb-47c8-893b-cde578301f9d.png)

[01:18] Azken Zutik: Game showed death screen immediately when I did that. However, log continued to update about me character being hungry and weak from hunger so I figured out it was still alive.
[23:44] igroglaz: hm... so you didn't RIP?
[01:18] Azken Zutik: Correct, no rip. Just death screen. Had to re-log in to fix.

**Comment by igroglaz** [comment] 2022-07-02 09:58
Additional note: CLAIRVOYANCE activation effect in T got such properties:

```
name:CLAIRVOYANCE
aim:0
power:22
effect:LIGHT_LEVEL
effect:TIMED_INC_NO_RES:PARALYZED
dice:3d1
effect:TIMED_INC_NO_RES:BLIND
dice:5+1d13
effect:TIMED_INC_NO_RES:IMAGE
dice:11+1d24
effect:NOURISH:DEC_BY
dice:5
msg:The {kind} form{s} an image in your mind...
desc:completely lights up and magically maps the current level, sensing all
desc: objects
```

**Comment by igroglaz** [comment] 2022-07-02 19:10
I suppose I got it.. NOURISH:DEC_BY should watch of for minimum nourishment.. and leave at least 1% if it is going to become less then 0.

**Comment by draconisPW** [comment] 2022-07-04 08:08
Checked in V and PWMA: DEC_BY sets food to 0% and starving state, you die the next turn from starvation. Can't reproduce the behavior with the bogus death screen.

Fix above does nothing as player_dec_timed() will call player_set_timed() with a negative value and the first thing player_set_timed() does is "v = MAX(v, (idx == TMD_FOOD)? 1: 0);" so it already sets the food counter to 1.

**Comment by draconisPW** [comment] 2022-07-04 09:38
No idea what could cause this, tombstone is only sent when the char is dead. Closing this as I will probably never be able to reproduce ever.

**Closed by draconisPW** 2022-07-04 09:38 UTC

**Comment by igroglaz** [comment] 2022-07-04 09:44
Actually I saw this happen before once or twice. Though don't remember did we made an attempt to fix it or not

**Comment by igroglaz** [comment] 2022-07-04 09:47
maybe to catch this bud we should add a check in 'tombstone' for certain case which might help debug? As in this picture we see negative values:

https://user-images.githubusercontent.com/39904162/176995624-361d85e0-7dda-4a9e-9d98-fd1cde62bb71.png

So if we will add check for negative values there and put a breakpoint - in case of triggering it - we might find the culprit

**Comment by igroglaz** [comment] 2022-07-04 09:59
also maybe an issue could be connected to the fact that dice for effect is different from actual value... eg
```
effect:NOURISH:DEC_BY
dice:5
```
in reality it's 500

**Comment by igroglaz** [comment] 2022-07-04 10:08
> tombstone is only sent when the char is dead

it also printed in netserver.c
```
int Init_setup(void)
{
    /* Initialize some values */
    Setup.frames_per_second = cfg_fps;
    Setup.min_col = SCREEN_WID;
    Setup.min_row = SCREEN_HGT;
    Setup.max_col = z_info->dungeon_wid;
    Setup.max_row = z_info->dungeon_hgt;

    /* Verify and load the splash screen */
    show_splashscreen();

    /* Verify and load the tombstone */
    print_tomb();

    /* Verify and load the winner crown */
    display_winner();

    return 0;
}
```

-----------------------------

Also maybe it's somekind of network glitch.. like wrong packet or something received by client and it shows wrong screen

**Comment by igroglaz** [comment] 2022-07-04 10:14
So getting back to the picture above:

![177129520-17d14bf1-45a0-4fd1-b8f5-503c774becae](https://user-images.githubusercontent.com/39904162/177134045-7555c3d8-c682-4c5a-a359-48a763a2e701.png)

Seems all this values are garbage..

So in netserver.c :
```
int Send_death_cause(struct player *p)
{
    connection_t *connp = get_connp(p, "death_cause");
    if (connp == NULL) return 0;

    return Packet_printf(&connp->c, "%b%s%hd%ld%ld%hd%hd%hd%s%s", (unsigned)PKT_DEATH_CAUSE,
        p->death_info.title, (int)p->death_info.lev, p->death_info.exp,
        p->death_info.au, (int)p->death_info.wpos.grid.y, (int)p->death_info.wpos.grid.x,
        (int)p->death_info.wpos.depth, p->death_info.died_from, p->death_info.ctime);
}
```

Stuff filled with garbage value. So if we will add breakpoint check for debug there which evaluate absurd values - we will be able to catch the bug.

**Comment by igroglaz** [comment] 2022-07-04 10:17
Something like 
if (p->death_info.lev < 1 || p->death_info.lev > 50)
; // breakpoint

**Comment by draconisPW** [comment] 2022-07-04 13:53
So yeah looking at the log it has nothing to do with losing 5% food from using the palantir since food meter was at "hungry" at the time (8%-14%) and turned into "weak" (4%-7%) at 164023. Player then went "faint" (1%-3%) at 164149, so a minute and a half later. Then "starving" (<1%) at 164312, so another minute and a half later. In that state, character starts losing hps until it drops below zero and gets killed (starvation itself doesn't kill even if food count reaches zero, so you can theoretically continue playing indefinitely if you keep healing constantly). In that case, message is Goodbye player ("Killed by starvation") and not Goodbye player ("client quit"). Did the player close client just at 0 hp before dying from starvation? Or maybe a missing packet just before sending the death screen?

**Comment by igroglaz** [comment] 2022-07-04 14:52
[17:50] igroglaz: please could you clarify - at which moment did you closed the client?
[17:50] Azken Zutik: After death screen appeared. Probably 30 seconds to a minute after it appeared to be more accurate.
