### ISSUE TITLE
allow to 'exit' from 'shop' to safe floor

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#213] opened 2020-06-29 06:49 UTC
right now if you speak to NPC and then push ESC to exit NPC dialog - game will put your character on any not-safe terrain. It forced me to add non-safe floors inside of shops and tavern as otherway you get teleported out of buildings. But having non-safe floors in shops makes it dangerous to stay afk in any place in the game, which is not fun :) Its good to be safe in tavern or in a shop.

/rfe
allow game to put your character on safe floor after you exit NPC dialogue
(but prevent to put you on top of another NPC.. as there are some NPCs which stay close to each other in tavern)

**Comment by draconisPW** [comment] 2020-06-30 14:02
I don't get this sorry. All floors in shops are marked as "FLOOR_SAFE" and pressing ESC finds any spot that is marked as any floor that doesn't have objects or monsters in it. If you get expelled outside, I just assume you have littered the Tavern with objects or defined tiles that are not floors.

Note: to distinguish the Tavern in the starting town, which is the starting point for every character, the feature "safe floor" is used and the flag SQUARE_VAULT is set, which prevents teleportation for obvious reasons. No building that has the "safe floor" terrain should contain NPCs. If you want to add NPCs to buildings, use a different terrain and set it with FLOOR_SAFE (for example: floor parquet 3 in the Tavern of Farfest works perfectly).

**Closed by draconisPW** 2020-06-30 14:02 UTC
Labels: enhancement

**Comment by igroglaz** [comment] 2020-06-30 14:13
"I just assume you have littered the Tavern with objects or defined tiles that are not floors."

Nope, I didn't. This problem exist not only in starting town but everywhere. Now you do not see it because I've added regular (not safe) floors in every building - so player won't be teleported outside after speaking with NPC. So right now inside of any building could appear monsters. You do not see them bacause there is a problem with monsters spawn atm (https://github.com/draconisPW/PWMAngband/issues/212)

So the problem is:

1) if you speak to NPC and then push ESC to exit NPC dialog
2) game can not put your character to  FLOOR_SAFE a shop
3) game will put your character on any not-safe terrain

I could turn on it on server to demonstrate, but them I need to make 'server' wipe to re-draw world map

**Comment by igroglaz** [comment] 2020-06-30 14:15
"(for example: floor parquet 3 in the Tavern of Farfest works perfectly)."

No, it doesn't. It's got non-safe terrain spots - so player will be able to get there after ESC (so monsters could spawn in tavern atm).

**Comment by igroglaz** [comment] 2020-06-30 14:19
"No building that has the "safe floor" terrain should contain NPCs. If you want to add NPCs to buildings, use a different terrain and set it with FLOOR_SAFE (for example: floor parquet 3 in the Tavern of Farfest works perfectly)."

Hm.. I think you are right there - I could use new flag "NO_GENERATION" to prevent monsters to spawn there. 

Thanks.

**Comment by draconisPW** [comment] 2020-06-30 14:27
I've just tested in debug mode and everything works as intended, I don't understand at all. Every floor inside the Tavern in Farfest are defined as FLOOR_SAFE, no monsters can be generated inside and when you speak to NPC and press ESC you are moved inside the tavern on an adjacent square. Your local copy is bugged then.

**Comment by igroglaz** [comment] 2020-06-30 14:31
It seems you missed this message: 

"No building that has the "safe floor" terrain should contain NPCs. If you want to add NPCs to buildings, use a different terrain and set it with FLOOR_SAFE (for example: floor parquet 3 in the Tavern of Farfest works perfectly)."

Hm.. I think you are right there - I could use new flag "NO_GENERATION" to prevent monsters to spawn there.

Thanks.

-------------
Considering:
"Every floor inside the Tavern in Farfest are defined as FLOOR_SAFE"
Nope, tavern in Farfest got non-safe floors. I've got there are two types of floors who look the same but got different properties... ;)

Anyway. It doesn't matter. I'll just make NO_GENERATION, remove safe_floor and it will work perfect :D
