### ISSUE TITLE
server crush 

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#195] opened 2020-05-14 07:41 UTC
log:
https://pastebin.com/WvwhpyvA

I suppose this crush it possible to investigate only with debug version; please could you release it, so I'll put it on the server

**Comment by draconisPW** [comment] 2020-05-14 08:12
"You dig in the rubble"

I'll try to see if it's not due to a problem with generating the treasure that can appear 10% of the time when digging rubble. I'll download the latest Tangaria lib files to check.

**Comment by igroglaz** [comment] 2020-05-14 09:52
hm.. I've assigned a lot of walls in terrain.txt with 'ROCK' flag instead of 'WALL' flag. eg ruins:

```
name:obj_grass L ruins
graphics:::s
priority:18
flags:TORCH | BORING | ROCK
info:0:2
################################################################################
short-desc:ruins
desc:.
```

Could it be the reason of this crush?

**Comment by draconisPW** [comment] 2020-05-14 14:01
Sorry can't reproduce :(

**Comment by igroglaz** [comment] 2020-05-15 08:16
yet another crush:
https://pastebin.com/B8NkqHTt

**Comment by igroglaz** [comment] 2020-05-15 14:34
I suppose that first crash was caused because player digged into border-wall without PERMANENT flag on it (I've just fixed it; added this flag everywhere). But second crash ( https://pastebin.com/B8NkqHTt ) looks strange.. as server died after starvated death.

**Comment by draconisPW** [comment] 2020-05-19 08:34
Can't reproduce, will need to install Builder 6 on the server and run it in debug mode to get the precise line of code that provokes the crash.

**Comment by igroglaz** [comment] 2020-05-19 17:48
yet another crush, weird one:
```
190520 011303 Invalid connection type requested from 4**.***.***.***
190520 091442 Invalid connection type requested from 4**.***.***.***
190520 160556 Welcome YAROSSS=tkach@LAPTOP-PHH41B20 (1***.***.***.***) (version 1408)
190520 160628 Shutting down (panic save).
190520 160628 Server panic info save succeeded!
```

**Comment by draconisPW** [comment] 2020-05-24 13:10
Crash when connecting back to the game is due to game trying to memorize out of bounds trap placement in player cave (rd_player_traps). I've added some check vs player_square_in_bounds_fully() like it is done for objects so the crash doesn't appear. This should never happen though, so there is probably a bug somewhere else and I need to know where. For this reason, I've added some log and we'll have to test this in debug mode.

**Comment by draconisPW** [comment] 2020-06-02 15:22
Seems the game doesn't crash anymore, but I've sighted a couple fixes in the V code related to monsters and monster groups that could provoke a crash and gonna fix those for next release. Closing this in the meantime. Keeping server in debug mode is enough for now.

**Closed by draconisPW** 2020-06-02 15:22 UTC
Labels: Critical, bug

**Comment by igroglaz** [comment] 2020-06-02 16:36
Yeah, it's great to have server always in debug mode! :bear:
