### ISSUE TITLE
show 'real' (negative) stats in character sheet

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#79] opened 2020-02-28 09:55 UTC
following this https://github.com/draconisPW/PWMAngband/issues/78 issue

/rfe to add 'real' (negative) stat parameters notes in character sheet, eg right now:
https://cdn.discordapp.com/attachments/596389778992398356/682887339890311179/stats.jpg

(1) - doesn't have info what bonuses exactly has this values (maybe it's a bug? should I create another ticket?)

(2) - shows some quite obvious info.. maybe to move it to 3rd page of character sheet ('C' -> 'm' -> 'm'); and put there instead 'real' stats info?

Also at (2) RB showed wrong (bug?): -10; but in gamedata dragons have -20 (https://tangaria.com/data/races/)

**Comment by draconisPW** [comment] 2020-02-28 14:11
As I said, polymorphed players have ALL race bonuses halved. It's not a bug to show "-10" when the actual modifier is "-20", since a Dragon is considered polymorphed. It would be the same if you play any race and drink from a fountain that would polymorph the character temporarily into a bat.

**Comment by draconisPW** [comment] 2020-03-12 10:56
Lemme try to figure this out...

1) This is simply the STR/INT/WIS/DEX/CON bonuses given by each equipment slot, I don't see anything wrong there...

2) Is fine, minimum value used is 3, maximum value used is 18/220

I don't see anything to change here, closing this.

**Closed by draconisPW** 2020-03-12 10:56 UTC
Labels: enhancement
