### ISSUE TITLE
Gold disappearing when dropped in house

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#80] opened 2020-02-28 13:50 UTC
https://www.youtube.com/watch?v=dv80MgaFFsM&t=14m31s

I had ~30k gold in that pile, but when I picked it up only 1 gold was taken... 

p.s.
just a speculation why it could be: maybe I took it while 'running' (the same problem as when character won't pick up inscribed arrows from the ground if you run)

**Comment by draconisPW** [comment] 2020-02-28 14:16
I've looked at the video and that's what you did:
- drop 1 gold in the house
- drop 300000 gold at the same spot, which was considered as all your gold

So it's either:
- second "drop gold" command removed gold from the character but didn't stack the result on the spot
- request to drop an amount greater than what the character was carrying removed gold from the character but considered the amount too much and dropped zero instead

I need to test this ASAP since it's some critical issue and make a new 1.3.0 release with the fix.

**Comment by draconisPW** [comment] 2020-02-28 16:05
I've managed to reproduce the problem... and gold simply doesn't stack on floor (not only in houses... but anywhere). If you drop gold then gold again on the same spot, the second amount is lost.

**Comment by draconisPW** [comment] 2020-02-28 16:50
Fixed in master, I'll try to report the fix to 1.3.0.

**Comment by draconisPW** [comment] 2020-03-06 11:03
Fixed in 1.3.0 too.

**Closed by draconisPW** 2020-03-06 11:03 UTC
Labels: bug
