### ISSUE TITLE
Fail to cast spell with CD

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#568] opened 2022-09-24 14:04 UTC
repro:
1) replace Mage class 1st spell with:

```
spell:Aging Hex:1:0:5:1:0
cooldown:2
effect:BOLT:TIME:0
dice:$B
expr:B:PLAYER_LEVEL:+ 1
desc:Causes magical aging to the target. Do not require mana.
desc: Cooldown 2 turns.
```

2) assign a macro: i) 'keymap by spell' at '+' key, like this:

![image](https://user-images.githubusercontent.com/39904162/192102198-62c451f8-e131-4025-b3cf-5c10d2ba8823.png)

3) now try to kill stuff by spamming this hotkey.. it will sometimes overflow to message string on top of the screen, like this:

![image](https://user-images.githubusercontent.com/39904162/192102055-c31c3228-9381-4c4a-aae9-06ae730cc59c.png)

**Comment by draconisPW** [comment] 2022-10-04 06:51
Unfortunately I cannot reproduce this locally. Must only happen when you connect to distant server with latency so the command is not processed fast enough and all the plusses are queued on the action line.

**Comment by igroglaz** [comment] 2022-10-04 07:43
Stuff which I've described in initial post is reproduced in local server, using native PWMA client/server.

**Comment by igroglaz** [comment] 2022-10-04 09:34
Ok, got exact repro:

before casting spell press numpad direction and then right on press spell hotkey. eg:
1) press right (numpad 6 key)
2) press right on '+'

this action toggle on/off this bug behaviour. demo:
[demo](https://youtu.be/cl_hG0z-4BE)

**Comment by draconisPW** [comment] 2022-10-04 09:51
I see. Maybe it's because "6 and +" is already considered as a macro, I'll check that.

**Comment by draconisPW** [comment] 2022-10-06 08:15
The "Action: xxx" message also appears when the spell has not been learned.

**Comment by draconisPW** [comment] 2022-10-06 09:28
Alright the reason for this is that if the command is m"Aging Hex"'. Since we're in a macro, everything in the command is processed sequentially. The first command processed is "m" (cast a spell), if the command is successful, it will use the rest as parameter for the spell (cast "Aging Hex" and use the quote as "aim at closest target"), if the command is unsuccessful (which is the case if you don't have learned the spell or if the spell is on cooldown) it will continue normally and interpret the rest as "Aging Hex"'. In this case, the double quote represents the command "Action:" and the rest will be interpreted as plain text as parameter for the action.

**Closed** 2022-10-06 10:11 UTC
