### ISSUE TITLE
Detect Monsters spell & "L"ook

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#328] opened 2021-03-27 21:26 UTC
With tileset player needs to "L" a lot (move view between map sectors). Problem is that spell "detect monsters" dissapear very fast, so player cant see monsters when moving screen with "L". It makes quite bad playing experience with caster class with tileset as it's super hard to understand where monsters located; while this problem isn't critical in ASCII.

/rfe save detected items when you move screen, so monsters revealed by the Detect Monsters spell will stay on the screen until the grids are redrawn. 

This issue was fixed in TomeNET 3-4 years ago

**Comment by draconisPW** [comment] 2021-03-29 06:53
No idea how to do this, putting in for future reference. Yesterday I tested the spell in MAngband and it's even worse, the list is cleared almost immediately, you can't even tell what you detected.

**Comment by igroglaz** [comment] 2021-03-29 09:50
I'm not sure, but maybe TomeNET made it in this commit:
https://github.com/TomenetGame/tomenet/commit/6b47eef4295eaecb5c370a2d55ee67fb10ba2575

**Comment by draconisPW** [comment] 2021-03-29 10:12
They didn't fix the problem, they just limited detection to the current panel. This is a solution though...

**Comment by igroglaz** [comment] 2021-03-30 10:26
`by just looking at the monster list since it tells if the mobs are north, south, east or west.`

erm?.. I don't have signs of monsters direction... just symbol, number and name, eg:
o 3 elite uruks
~ 1 flying skull

**Comment by igroglaz** [comment] 2021-03-30 14:01
I don't see it for unique monsters either:
q [U] The wounded bear  (asleep)

**Comment by draconisPW** [comment] 2021-03-30 14:16
It's there, so I assume your term is too small and the info is hidden (it's on the right).

**Comment by igroglaz** [comment] 2021-03-30 15:58
my term is quite big - half of the screen: https://cdn.discordapp.com/attachments/699917093717671946/826485156612538428/0.jpg

but to show directions player need to have enormous width:
https://cdn.discordapp.com/attachments/699917093717671946/826485167001698334/1.png

I suppose you don't struggle from this problem as you don't play with tileset

**Comment by igroglaz** [comment] 2021-03-30 16:11
my term is quite big - half of the screen: https://cdn.discordapp.com/attachments/699917093717671946/826485156612538428/0.jpg

but to show directions player need to have enormous width:
https://cdn.discordapp.com/attachments/699917093717671946/826485167001698334/1.png

maybe it's possible to align directions closer to monster names on the left?

**Comment by draconisPW** [comment] 2021-06-07 13:29
Duplicate of #135.

**Closed by draconisPW** 2021-06-07 13:29 UTC
Labels: enhancement
