### ISSUE TITLE
SDL client: add OGG file support for sounds

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#294] opened 2020-12-27 21:00 UTC
it seems status effects sounds are broken (the reason why I died in my past stream: https://www.youtube.com/watch?v=6WHxsF5zByM - I was blinded, but the game didn't made the sound about it)

**Comment by igroglaz** [comment] 2020-12-27 21:04
in Tangaria .prf https://github.com/igroglaz/Tangaria/blob/master/lib/customize/sound.prf

```
# You become blind.
#sound:blind:pls_tone_conk
sound:blind:t/blind t/blind1 t/blind2

# You become confused.
#sound:confused:pls_man_ugh
sound:confused:t/confused
```


everything worked fine before...

**Comment by igroglaz** [comment] 2020-12-29 16:22
moved files from t/ folder to parent folder.. will see will it help

**Comment by igroglaz** [comment] 2020-12-30 13:16
I suppose folder wasn't an issue.

example of problems with condition's sounds:
https://www.youtube.com/watch?v=6WHxsF5zByM&t=11m57s

1st blind didn't had sound at all. second had "bl..".. So in ~50% cases you won't hear condition if there are a lot of actions involved as they interrupt sounds. Condition sounds should play without overlapping/disabling by other sounds...

**Comment by draconisPW** [comment] 2021-01-04 07:51
Frankly I have no idea how to do that there is no priority for sounds so next sound will overlap prior one. If you get blinded and a millisecond later you hit something the hit sound will be heard.

**Comment by igroglaz** [comment] 2021-01-08 17:52
..So playing with sounds actually is a bad habit atm as it leads to death. You can't rely on sounds in terms of conditions, which is the main purpose of the whole sound system 😭

**Comment by draconisPW** [comment] 2021-01-11 13:43
I just tested again. This problem only happens with SDL, the Win client works as intended and sounds don't interrupt each other.

**Comment by draconisPW** [comment] 2021-01-11 14:13
Looked at the SDL_mixer library and Mix_PlayMusic() only works with ONE sound, there's no way to replicate the Win sound with SDL. For that we would have to port all files to .ogg and use Mix_PlayChannel() with multiple channels and rewrite the whole sound module. And I clearly don't have time for that so unless V or Mang do this, it won't be implemented.

**Comment by igroglaz** [comment] 2021-01-11 14:44
Great that you've investigated into this issue, thanks 👍 I will port all files to .ogg with some additional mastering. 

Maybe if it will be easier - we could have two separate sound systems - old one for Win client and new one for SDl

**Comment by draconisPW** [comment] 2021-01-11 15:00
There are already 2 separate sound systems, each module uses a sound hook.

**Comment by draconisPW** [comment] 2021-01-11 15:01
Misclick ;)

**Comment by igroglaz** [comment] 2021-01-11 18:39
@flambard-took maybe you know solution to this issue?

**Comment by s88100** [comment] 2021-01-12 11:48
maybe this tutorial will help https://lazyfoo.net/SDL_tutorials/lesson11/index.php

**Comment by s88100** [comment] 2021-01-12 14:16
mp3 format **Mix_PlayMusic(** to play music, and ogg **Mix_PlayChannel(** for sound effects.
I converted mp3 to ogg
`for i in *.mp3; do ffmpeg -i "$i" "${i%.*}.ogg"; done`
and added music files amb_bell_metal1.mp3, amb_door_iron.mp3. Music playing with sounds

**Comment by draconisPW** [comment] 2021-01-12 16:39
Unfortunately I converted all files to .ogg and enabled reading sounds from ogg files and it doesn't work: "unrecognized sound file type".

**Comment by s88100** [comment] 2021-01-12 19:10
oh, yes snd-win.c there is no .ogg
on SDL client needed {".mp3", SDL_CHUNK}, for support mixing channel Mix_PlayChannel(1 ,2,3... example ambient_channel https://github.com/TomenetGame/tomenet/blob/master/src/client/snd-sdl.c#L1770 
and the algorithm for load_sample_sdl sample->sample_data.chunk 1,2,3... https://github.com/draconisPW/PWMAngband/blob/master/src/client/snd-sdl.c#L172

**Comment by s88100** [comment] 2021-01-13 07:24
I added a comment `//Mix_HaltChannel(-1);` https://github.com/draconisPW/PWMAngband/blob/master/src/client/snd-sdl.c#L170  Since it's set to -1, Mix_PlayChannel() just looks for the first channel that's available and plays the sound. It work with ogg files, loaded multiple sound effects.
But I couldn't load mp3 in Mix_PlayChannel( , Mix_Init(MIX_INIT_MP3) to initialize decoders and Mix_Quit() to close the decoders. https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_9.html
Maybe you need add algorithm support ogg (case WIN_OGG) in https://github.com/draconisPW/PWMAngband/blob/master/src/client/snd-win.c#L32 it is possible to add a a CASE to load music (mini player for dungeons)

**Comment by draconisPW** [comment] 2021-01-13 08:15
Doesn't matter.

1) SDL client: Mix_LoadWAV() doesn't recognize mp3 files, and even if it says it works with ogg files, it doesn't, you get "unrecognized sound file type" error (returns NULL)
2) Win client: I added "ogg" to supported_sound_files array but mciSendCommand() doesn't recognize ogg files, you get the same error (returns NULL)

This is probably due to not having an OGG library to actually play the sounds. People on Linux have libvorbis.so, I need something similar for Windows.

**Comment by s88100** [comment] 2021-01-13 10:39
TomeNET uses ogg and Windows depends on libogg-0.dll,libvorbis-0.dll,libvorbisfile-3.dll, smpeg.dll (for mp3) https://tomenet.eu/guide.php?chapter=2
_Dependencies:
-libsdl_mixer may complain about missing dependencies (at least Ogg Vorbis is required for TomeNET, since it's the official audio format - the rest is only needed if you add custom audio files in the according file formats):
-Ogg Vorbis library (www.xiph.org -> libogg and libvorbis) for OGG file support, which is what the official TomeNET audio files are.
-SMPEG library (icculus.org/smpeg) for MP3 file support. (libsdl_mixer's configure script May also list additional notes regarding the environment variable SMPEG_CONFIG, don't miss them.)_

**Comment by draconisPW** [comment] 2021-01-13 11:04
Now I get: Mix_Init() error -- mixer not built with ogg vorbis support.

**Comment by draconisPW** [comment] 2021-01-13 11:11
Of course, if I want SDL_mixer to work with OGG files, I need to compile it with OGG support...

**Comment by draconisPW** [comment] 2021-01-13 13:27
IT WORKS!

**Comment by draconisPW** [comment] 2021-01-13 13:47
Win client still doesn't support OGG files so I'll have to package both mp3 files (for the Win client) and ogg files (for the SDL client). The load_sound() method iterates over valid file extensions, so I just need to put mp3 first in snd-win and ogg first in snd-sdl so the proper file is loaded.

**Comment by draconisPW** [comment] 2021-01-13 14:07
Implemented. Win client uses mp3 files, SDL client uses ogg files. Sounds now play till the end and are not interrupted by other sounds.

**Closed by draconisPW** 2021-01-13 14:07 UTC
Labels: enhancement

**Comment by igroglaz** [comment] 2021-06-18 18:35
it seems this problem again there. sounds interrupted  https://youtu.be/HfFvuFdvkDY?t=632 must play all sound (open door + arrr + hit)

https://github.com/draconisPW/PWMAngband/issues/380

**Comment by draconisPW** [comment] 2021-06-21 06:56
Perhaps Mix_Volume() interacting with this? I'll check...

**Comment by draconisPW** [comment] 2021-06-21 08:23
Can't reproduce, works perfectly for me.
