### ISSUE TITLE
ID bug (poison potion)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#567] opened 2022-09-12 08:51 UTC
repro in PWMA:
1) create a !poison potions (to generate not neutr.poison, but poison potion: choose to generate !conf and '+') with admin char by standing in the walls (so it will drop on the ground not IDed)
2) generate ID scrolls and put on the ground
2) enter the game with other char and drink this potion from the ground - it will say that it's !poison
3) try to read ID scroll and you will see that it's still suggest you to ID !poison

**Comment by draconisPW** [comment] 2022-09-12 10:47
That's because potions of poison have poison brand and need to be thrown at enemies to discover the brand. Dunno if that's really a bug (there was same issue with flasks of oil before fire brand was removed in V and hardcoded as 3x damage).

**Comment by igroglaz** [comment] 2022-09-12 11:13
It feels like a bug to me - as game kinda wants you to use valuable scrolls of ID on dull item which you already know :) Maybe we should also hardcode !poison, it will solve the issue

Another strange thing that player can't put on sale Resist poison potions
![image](https://user-images.githubusercontent.com/39904162/189639082-08820f45-a8ed-43df-81a6-0b3bd88f69fb.png)
 I suppose this 2 issues might be connected (not sure in which way)

**Comment by draconisPW** [comment] 2022-09-12 13:06
I've hardcoded the poison effect on potions of poison to avoid ID issues.

**Comment by draconisPW** [comment] 2022-09-12 13:11
Can't reproduce the N/A on resist poison, closing this.

**Closed by draconisPW** 2022-09-12 13:11 UTC
